"""l

Revision ID: 5f1f94847a88
Revises: eb3ddf630cd2
Create Date: 2025-07-05 02:39:57.171618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1f94847a88'
down_revision: Union[str, Sequence[str], None] = 'eb3ddf630cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro_treinamento',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('proprietario', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('centro_treinamento')
    op.drop_constraint(op.f('atletas_centro_treinamento_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centro_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('categorias', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_centro_treinamento_id_fkey'), 'atletas', 'centro_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.create_table('centro_treinamento',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('proprietario', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name=op.f('centro_treinamento_pkey')),
    sa.UniqueConstraint('nome', name=op.f('centro_treinamento_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('centro_treinamento')
    # ### end Alembic commands ###
