"""add_on_delete_cascade_to_categoria_fk

Revision ID: bc80c22ef03a
Revises: 5f1f94847a88
Create Date: 2025-07-05 04:53:07.713086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc80c22ef03a'
down_revision: Union[str, Sequence[str], None] = '5f1f94847a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atletas_categoria_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'], ondelete='CASCADE')
    op.drop_column('categorias', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_categoria_id_fkey'), 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###
